# the current file define the syncing and options related to the "services" created from the app-of-apps
# this is different from the one in the "terraform module", this one in here is responsible of syncing "services" in the app-of-apps module
# while the one in the terraform is responsible of creating the application that connect those services to it
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
  # use the "finalizers" to remove any resources when the yaml file is changed/deleted, by default ArgoCD does not delete resources automatically
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: ssh://git@github.com/JoudAwad97/app-of-apps.git
    # path of the service in the files
    path: retail-store-ui/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: app-1=thejoud1997/app-1
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/app-1.update-strategy: latest
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: ssh://git@github.com/JoudAwad97/app-of-apps.git
    # path of the service in the files
    path: app-1/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: app-2=thejoud1997/app-2
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/app-2.update-strategy: latest
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: ssh://git@github.com/JoudAwad97/app-of-apps.git
    # path of the service in the files
    path: app-2/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stateful
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: ssh://git@github.com/JoudAwad97/app-of-apps.git
    # path of the service in the files
    path: stateful/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-3
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: app-3=thejoud1997/app-3
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/app-3.update-strategy: latest
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: ssh://git@github.com/JoudAwad97/app-of-apps.git
    # path of the service in the files
    path: app-3/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
