# the current file define the syncing and options related to the "services" created from the app-of-apps
# this is different from the one in the "terraform module", this one in here is responsible of syncing "services" in the app-of-apps module
# while the one in the terraform is responsible of creating the application that connect those services to it
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: https://github.com/JoudAwad97/app-of-apps
    # path of the service in the files
    path: retail-store-ui/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: https://github.com/JoudAwad97/app-of-apps
    # path of the service in the files
    path: app-1/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: https://github.com/JoudAwad97/app-of-apps
    # path of the service in the files
    path: app-2/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stateful
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: https://github.com/JoudAwad97/app-of-apps
    # path of the service in the files
    path: stateful/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-3
  # namespace should be the same one where you have ArgoCD installed
  namespace: argocd
spec:
  # the same name of the project where you are extending this services
  project: default
  source:
    repoURL: https://github.com/JoudAwad97/app-of-apps
    # path of the service in the files
    path: app-3/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  # service syncing options
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
