---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  # only allow to change the applications.yaml file from the base app-of-apps module
  - applications.yaml
  - namespace.yaml
  - https://github.com/argoproj/argo-rollouts/releases/latest/download/notifications-install.yaml
