version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "$(aws ecr get-login --no-include-email --region $AWS_REGION)" | docker login -u AWS --password-stdin 123456789012.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Commit hash is $COMMIT_HASH"
      - IMAGE_TAG_LATEST=latest
      - REPO_NAME=$(echo $CODEBUILD_SOURCE_REPO_URL | sed 's/.*\///' | sed 's/.git//')
      - REPOSITORY_NAME=thejoud1997/$REPO_NAME

  build:
    commands:
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG_LATEST .
      - docker tag $REPOSITORY_NAME:$IMAGE_TAG_LATEST $REPOSITORY_NAME:$IMAGE_TAG_HASH

  post_build:
    commands:
      - docker push $REPOSITORY_NAME:$IMAGE_TAG_LATEST
      - docker push $REPOSITORY_NAME:$IMAGE_TAG_HASH

cache:
  paths:
    - "/root/.docker/*"
