version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo "Reading current version..."
      - CURRENT_VERSION=$(cat package.json | jq -r .version)
      - MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
      - MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
      - PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/dev" ]; then
            PATCH=$((PATCH + 1))
        elif [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/staging" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
        elif [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/prod" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
        fi
      - NEW_VERSION="$MAJOR.$MINOR.$PATCH-$CODEBUILD_WEBHOOK_TRIGGER"
      - echo "New version: $NEW_VERSION"
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$NEW_VERSION .
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $REPOSITORY_URI:$NEW_VERSION
      - echo "Updating VERSION file..."
      - echo $NEW_VERSION > VERSION
      - git add VERSION
      - git commit -m "Update to version $NEW_VERSION"
      - git push origin $CODEBUILD_WEBHOOK_TRIGGER
