apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-rds
  namespace: retail-store
spec:
  hosts:
    - database-1.cpgwvhcnpddn.us-east-2.rds.amazonaws.com
  ports:
    - number: 3306
      name: tcp
      protocol: TCP
  resolution: STATIC
