apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mysql-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
    - port:
        number: 3306
        name: tcp
        protocol: TCP
      hosts:
        - "*.rds.amazonaws.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-external
spec:
  hosts:
    - "database-1.cpgwvhcnpddn.us-east-2.rds.amazonaws.com"
  addresses:
    - 10.80.0.0/16
  ports:
    - name: tcp
      number: 3306
      protocol: tcp
  location: MESH_EXTERNAL
