apiVersion: v1
kind: Service
metadata:
  name: auth-active
  namespace: retail-store
spec:
  selector:
    app: auth
  ports:
    - name: https
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-preview
  namespace: retail-store
spec:
  selector:
    app: auth
  ports:
    - name: https
      port: 80
      targetPort: 3000
  type: ClusterIP
