apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: retail-store
  labels:
    app: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a-container
          image: nginx:latest
