apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  # the namespace here is also required
  namespace: retail-store
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: service-a-container
          env:
            - name: ENVIRONMENT
              value: "development"
