---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
  namespace: istio-system
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: https
        protocol: HTTP
      hosts:
        - "*"
---
## Deploy Application load balancer and point it to the ingress gateway of the istio
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-name: alb-external-ingress
    # alb.ingress.kubernetes.io/subnets: subnet-0c11109d0b67a60b7, subnet-0d42b2dbf61968c87, subnet-058587473f3c14f4e
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # alb.ingress.kubernetes.io/target-type: instance
  name: gw-ingress
  namespace: istio-system
  labels:
    app: alb-external-ingress
spec:
  rules:
    - http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: app-1-active
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: https
  namespace: retail-store
spec:
  hosts:
    - "*"
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            prefix: /db
      route:
        - destination:
            host: app-3-active.retail-store.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /auth
      route:
        - destination:
            host: auth.retail-store.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-1-active.retail-store.svc.cluster.local
            port:
              number: 80
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: enable-mtls
  namespace: retail-store
spec:
  mtls:
    mode: STRICT
