---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: custom-gateway
spec:
  selector:
    istio: gateway # should match the label on the "pod" in the "istio-system" for the "gateway" deployment
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*" # Domain name of the external website
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: path-routing
spec:
  hosts:
    - "*"
  gateways:
    - custom-gateway
  http:
    - match:
        - uri:
            prefix: /*
      route:
        - destination:
            host: app-1.retail-store.svc.cluster.local
            port:
              number: 80
# ---
# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: enable-mtls
#   namespace: retail-store
# spec:
#   mtls:
#     mode: STRICT
