apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-ui
spec:
  template:
    spec:
      containers:
        - name: retail-store-ui
          env:
            - name: "CURRENT_ENV"
              value: "DEV"
