apiVersion: v1
kind: Service
metadata:
  name: retail-store-ui-service
  namespace: retail-store
spec:
  selector:
    app: retail-store-ui
  ports:
    - name: https
      port: 80
      targetPort: 8080
  type: ClusterIP
