# adding this here will make it generally access to all the other files in the base (instead of individually define it)
namespace: retail-store
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
resources:
- https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
- https://github.com/argoproj/argo-rollouts/releases/latest/download/notifications-install.yaml
