apiVersion: v1
kind: Service
metadata:
  name: app-1-active
  namespace: retail-store
spec:
  selector:
    app: app-1
  ports:
    - name: https
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-preview
  namespace: retail-store
spec:
  selector:
    app: app-1
  ports:
    - name: https
      port: 80
      targetPort: 3000
  type: ClusterIP
