apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3
  namespace: retail-store
  labels:
    app: app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      annotations:
        #sidecar.istio.io/rewriteAppHTTPProbers: "false"
        #traffic.sidecar.istio.io/excludeOutboundPorts: "3306"
      labels:
        app: app-3
        db: rds
        auth: custom
        version: safe
    spec:
      serviceAccountName: app-3
      containers:
        - image: thejoud1997/app-3:latest
          name: app-3
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-sealed-db
                  key: password
            - name: DB_SEALED_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalog-sealed-db
                  key: username
          volumeMounts:
            - name: app-3-secret
              readOnly: true
              mountPath: /mnt/domino-api-secrets
      volumes:
        - name: app-3-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
