apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: retail-store
spec:
  provider: aws
  secretObjects:
    - secretName: k8s-secret
      type: Opaque
      data:
        - objectName: db_host
          key: DB_HOST
        - objectName: db_username
          key: DB_USER
  parameters:
    objects: |
      - objectName: domino-dev/domino-api
        objectType: secretsmanager
        objectAlias: domino-api-secrets
        jmesPath:
            - path: DB_HOST
              objectAlias: db_host
            - path: DB_USER
              objectAlias: db_username
